"""部门描述

Revision ID: 29d80dbd505e
Revises: c2616adadbc7
Create Date: 2019-06-14 22:47:21.971773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d80dbd505e'
down_revision = 'c2616adadbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('describe', sa.String(length=512), nullable=False, comment='部门描述'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'describe')
    # ### end Alembic commands ###
